// Platform presets. Each preset describes the recommended output for a platform.
//
// safeArea values are fractions (0..1) of the frame that should be kept clear of
// text, because platform UI elements (captions, action buttons, profile) sit
// there. Templates read these margins so on-screen text never lands under the UI.
//
// theme carries a per-platform accent colour and a default card background so
// output looks tailored to each platform. accent is used for highlights and bars,
// cardBg is the fallback background for still cards when no image is supplied.
//
// To add a platform: append an object here with a unique id. Nothing else in the
// core needs to change. See CONTRIBUTING.md for the field contract.

export const PRESETS = [
  {
    id: 'tiktok',
    label: 'TikTok',
    kind: 'video',
    width: 1080,
    height: 1920,
    fps: 30,
    maxDuration: 60,
    container: 'mp4',
    vcodec: 'libx264',
    acodec: 'aac',
    vbitrate: '8M',
    safeArea: { top: 0.06, bottom: 0.2, left: 0.05, right: 0.12 },
    theme: { accent: '#FE2C55', cardBg: '#16161d' },
  },
  {
    id: 'instagram-reels',
    label: 'Instagram Reels',
    kind: 'video',
    width: 1080,
    height: 1920,
    fps: 30,
    maxDuration: 90,
    container: 'mp4',
    vcodec: 'libx264',
    acodec: 'aac',
    vbitrate: '8M',
    safeArea: { top: 0.07, bottom: 0.2, left: 0.05, right: 0.12 },
    theme: { accent: '#E1306C', cardBg: '#1a1320' },
  },
  {
    id: 'youtube-shorts',
    label: 'YouTube Shorts',
    kind: 'video',
    width: 1080,
    height: 1920,
    fps: 30,
    maxDuration: 60,
    container: 'mp4',
    vcodec: 'libx264',
    acodec: 'aac',
    vbitrate: '10M',
    safeArea: { top: 0.06, bottom: 0.16, left: 0.05, right: 0.1 },
    theme: { accent: '#FF0033', cardBg: '#1a0f12' },
  },
  {
    id: 'instagram-post',
    label: 'Instagram Post',
    kind: 'image',
    width: 1080,
    height: 1350,
    fps: 30,
    maxDuration: 0,
    container: 'jpg',
    vcodec: 'mjpeg',
    acodec: 'aac',
    vbitrate: '0',
    safeArea: { top: 0.06, bottom: 0.06, left: 0.06, right: 0.06 },
    theme: { accent: '#E1306C', cardBg: '#241726' },
  },
  {
    id: 'linkedin-post',
    label: 'LinkedIn Post',
    kind: 'image',
    width: 1200,
    height: 1200,
    fps: 30,
    maxDuration: 0,
    container: 'jpg',
    vcodec: 'mjpeg',
    acodec: 'aac',
    vbitrate: '0',
    safeArea: { top: 0.08, bottom: 0.08, left: 0.08, right: 0.08 },
    theme: { accent: '#0A66C2', cardBg: '#0b2239' },
  },
  {
    id: 'x-post',
    label: 'X / Twitter Post',
    kind: 'image',
    width: 1600,
    height: 900,
    fps: 30,
    maxDuration: 0,
    container: 'jpg',
    vcodec: 'mjpeg',
    acodec: 'aac',
    vbitrate: '0',
    safeArea: { top: 0.09, bottom: 0.09, left: 0.07, right: 0.07 },
    theme: { accent: '#1D9BF0', cardBg: '#15202b' },
  },
  {
    id: 'facebook-post',
    label: 'Facebook Post',
    kind: 'image',
    width: 1200,
    height: 1200,
    fps: 30,
    maxDuration: 0,
    container: 'jpg',
    vcodec: 'mjpeg',
    acodec: 'aac',
    vbitrate: '0',
    safeArea: { top: 0.08, bottom: 0.08, left: 0.07, right: 0.07 },
    theme: { accent: '#1877F2', cardBg: '#0e1b2e' },
  },
];
